import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profile from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='w-full min-h-screen flex items-center text-dark '>
        <Layout className='pt-0'>
          <div className='flex justify-between items-center w-full'>
            <div className='w-1/2'>
              <Image src={profile} alt='profile' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col justify-center items-center self-center'>
              <AnimatedText text={"Turning Vision Into Reality With Code And Design."} className='!text-5xl !text-left'/>
              <p>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
